### ISSUE TITLE
Error in Log: invalid character ' ' in string escape code

### ISSUE THREAD

**Issue by neuhausf** [camptocamp/bivac#325]
Hi
I'm using bivac to backup a bunch of docker volumes. Bivac runs as docker container itself, using the following docker-compose.yml (latest was version 2.1.0):
```
version: '2' 
services:
  bivac:
    image: camptocamp/bivac:latest
    command: manager
    container_name: bivac
    restart: always
    ports:
      - "8182:8182"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/backups:/var/backups"
    environment:
      BIVAC_SERVER_PSK: my-psk
      RESTIC_PASSWORD: my-password
      BIVAC_TARGET_URL: /var/backups
      BIVAC_AGENT_IMAGE: camptocamp/bivac:latest
```
The backup process seems to work properly - the restic repo is created under `/var/backups/my.server.net` of the docker host.

But if I use `docker-compose logs`, I see the following errors:
https://pastebin.com/XxCfHPWY

First a warning
```
[36mbivac    |[0m time="2019-08-26T05:56:23Z" level=warning msg="failed to unmarshal agent output: invalid character ' ' in string escape code -> ` ... big output as in the above pastebin ... `
```
followed by an error
```
[36mbivac    |[0m time="2019-08-26T05:56:23Z" level=error msg="failed to backup volume: invalid character ' ' in string escape code" ` ... big output as in the above pastebin ... `
```

Do you see any issues?

**Comment by neuhausf** [comment]
@raphink 
If I look into your code (without understanding Go ;)) then it seems like unmarshalling the output fails. The output itself (from restic?) seems to look fine. Is my naming causing issues? Can I (should I) reduce restic logging to work around the unmarshalling issue?

**Comment by dhilgarth** [comment]
I just saw the same issue in the logs. As far as I can tell, there is a space character in the middle of the JSON string at an unexpected location. In my case, it was between a backslash and the corresponding double quote that it escaped.  
I found it by copying the text from the bivac log and assigning it to a variable. I used Javascript. Then, I tried to use `JSON.parse` on that variable and got an error message pointing to a specific location in that string.  

The original string in the log looks like this:

    1f\\\"},{\\\"time\\ \":\\\"2019-08-29T11:17:23.76133

You can see the space after the double backslash after `time`.  
Assigning it to a variable results in this:  

    1f\"},{\"time\ ":\"2019-08-29T11:17:23.76133

Is this a problem with concating multiple strings?

**Comment by cryptobioz** [comment]
Hi @neuhausf, @dhilgarth, sorry for the late response...
The default behavior of Bivac is to pass through the orchestrator to read the Bivac agents' logs. This works most of the time but sometimes, for reasons I can't grasp very well, the agents' output may be truncated (which cause an error when Bivac tries to unmarshal it).
To avoid this, we implemented a basic _logging_ system so the agent can send its logs directly to the manager. To do so, you just have to set the environment variable `BIVAC_LOG_SERVER` with, as value, the address and the port of your Bivac container (e.g. http://bivac:8182).

**Comment by dhilgarth** [comment]
@cryptobioz Where should we set this environment variable?

**Comment by cryptobioz** [comment]
On the Bivac container. If this variable is set, the _manager_ will deploy the agents with a special parameter which make them send their logs directly to the manager through the API.

**Comment by reberinformatik** [comment]
Whats the hostname of the bivac container? It seems to be random. Your [unit test](https://github.com/camptocamp/bivac/blob/cc61c98affc0c9c358299abeb15d98520f64dcfd/test/integration/cattle/tests/01_basic#L82) seems to address the logserver by its `INTERNAL_IP`.

**Comment by cryptobioz** [comment]
It depends on your environment. For example, if you deploy Bivac via a docker-compose, I guess setting a `container_name` and use it as hostname should do the trick.

**Comment by cryptobioz** [comment]
But though, use the log server by default and let Bivac manage the "IP discovery" part is something that could be automated and integrated to the core. I'll think about that...

**Comment by dhilgarth** [comment]
That's not working for me.

Commands and logs:

```
daniel@linux-host:/opt/docker$ docker exec -it docker_backup-bivac_1 bash
root@c375879a99ae:/# bivac backup docker_jira2-data
Backing up `docker_jira2-data'...
ID: docker_jira2-data
Name: docker_jira2-data
Mountpoint: /var/lib/docker/volumes/docker_jira2-data/_data
Backup date: 2019-10-11 15:40:26
Backup status: Unknown
Logs:

        testInit
        init
        backup
        forget
root@c375879a99ae:/# bivac backup docker_jira2-data
Backing up `docker_jira2-data'...
ID: docker_jira2-data
Name: docker_jira2-data
Mountpoint: /var/lib/docker/volumes/docker_jira2-data/_data
Backup date: 2019-10-11 15:40:26
Backup status: Unknown
Logs:

        testInit
        init
        backup
        forget
root@c375879a99ae:/# exit
exit
daniel@linux-host:/opt/docker$ ./show-log.sh backup-bivac
WARNING: Some networks were defined but are not used by any service: vpn
Attaching to docker_backup-bivac_1
backup-bivac_1             | 2019-10-11T16:38:47.604364600Z time="2019-10-11T16:38:47Z" level=debug msg="Trying to detect orchestrator based on environment..."
backup-bivac_1             | 2019-10-11T16:38:47.701514800Z time="2019-10-11T16:38:47Z" level=debug msg="Starting volume manager..."
backup-bivac_1             | 2019-10-11T16:38:47.701557800Z time="2019-10-11T16:38:47Z" level=info msg="Starting backup manager..."
backup-bivac_1             | 2019-10-11T16:38:47.705044700Z time="2019-10-11T16:38:47Z" level=info msg="Listening on 0.0.0.0:8182"
backup-bivac_1             | 2019-10-11T16:41:27.802635800Z time="2019-10-11T16:41:27Z" level=debug msg="Backup manually requested." hostname=linux-host volume=docker_jira2-data
backup-bivac_1             | 2019-10-11T16:42:46.311546500Z time="2019-10-11T16:42:46Z" level=debug msg="Backup manually requested." hostname=linux-host volume=docker_jira2-data
```


docker-compose file:

```version: "3.7"

services:
  backup-bivac:
    image: camptocamp/bivac:2.1.0
    command: "manager -v"
    environment:
      AZURE_ACCOUNT_NAME: sovartobackups
      AZURE_ACCOUNT_KEY: ${AZURE_ACCOUNT_KEY}
      BIVAC_TARGET_URL: azure:backup-by-bivac:/
      RESTIC_PASSWORD: ${BACKUP_PASSPHRASE}
      BIVAC_SERVER_PSK: abc
      BIVAC_LOG_SERVER: http://backup-bivac:8182
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


```

**Comment by cryptobioz** [comment]
@dhilgarth looks like you didn't set a `container_name`. Could you add `container_name: backup-bivac` to your composition and retry?

**Comment by dhilgarth** [comment]
Didn't help :-(

**Comment by cryptobioz** [comment]
Thanks for this information, it's interesting... I gonna look on my side and get back to you as soon as possible.

**Comment by dhilgarth** [comment]
Let me know if I can provide any more info, logs, etc.

**Comment by cryptobioz** [comment]
Well, I figured out you cannot use the log server easily with docker-compose. The simplest workaround I found is to expose the port 8182 and use the `docker0` IP address as log server address.

For example:
```yaml
services:
  bivac:
    ...
    ports:
      - "8182:8182"
    environment:
      ...
      BIVAC_LOG_SERVER: http://[IP_ADDRESS]:8182
```

But I really don't like this solution and would rather understand what's wrong with the agent's output. I'll continue to dig into the code and come back to you asap.

**Comment by cryptobioz** [comment]
@neuhausf @dhilgarth As I cannot reproduce your behavior, would you please try to backup your volumes with the image `camptocamp/bivac:2.1.0-encoded-output`? I'm trying to figure out where the bug exactly comes from...

**Comment by dhilgarth** [comment]
> manifest for camptocamp/bivac:2.1.0-encoded-output not found

**Comment by cryptobioz** [comment]
My bad, not pushed, sorry... It should work now.

**Comment by dhilgarth** [comment]
The container did work now, however, I am still getting the same error on some volumes.
I have sent an email with a log file, maybe it helps.
From what I see, it looks like it receives the JSON object in multiple parts and then concats them. The problem seems to be, that each part starts with a space. The very first character of the JSON in the log also is a space

**Comment by cryptobioz** [comment]
@neuhausf @dhilgarth Do you have a special logging configuration in your Docker config (`/etc/docker/daemon.json`)?

I updated the image `camptocamp/bivac:2.1.0-encoded-output`, would you retry to backup your volumes please?

**Comment by neuhausf** [comment]
@cryptobioz Thanks for investigating this issue. I pulled your new image. Now I get another error while (manually) backing up a container:

Bash in docker container:
```
root@1fee0e27157c:/# bivac backup teamcity_teamcity-data
Backing up `teamcity_teamcity-data'...
ERRO[0012] failed to backup volume: failed to connect to the remote Bivac instance: failed to send request: Post http://127.0.0.1:8182/backup/teamcity_teamcity-data?force=false: EOF
```
Docker Host:
```
root@vmi284178:/srv/bivac# docker-compose logs
Attaching to bivac
bivac    | time="2019-10-16T11:32:46Z" level=info msg="Listening on 0.0.0.0:8182"
bivac    | time="2019-10-16T11:32:46Z" level=info msg="Starting backup manager..."
bivac    | 2019/10/16 11:33:30 http: panic serving 127.0.0.1:42840: interface conversion: interface {} is string, not map[string]interface {}
bivac    | goroutine 118 [running]:
bivac    | net/http.(*conn).serve.func1(0xc000179400)
bivac    |      /usr/local/go/src/net/http/server.go:1769 +0x139
bivac    | panic(0x1371720, 0xc0004616e0)
bivac    |      /usr/local/go/src/runtime/panic.go:522 +0x1b5
bivac    | github.com/camptocamp/bivac/internal/manager.(*Manager).updateBackupLogs(0xc000156d80, 0xc000458120, 0x15042f4, 0x7, 0x12d4c20, 0xc0001c1538)
bivac    |      /go/src/github.com/camptocamp/bivac/internal/manager/backup.go:159 +0x72b
bivac    | github.com/camptocamp/bivac/internal/manager.backupVolume(0xc000156d80, 0xc000458120, 0x0, 0x0, 0x0)
bivac    |      /go/src/github.com/camptocamp/bivac/internal/manager/backup.go:87 +0xa13
bivac    | github.com/camptocamp/bivac/internal/manager.(*Manager).BackupVolume(0xc000156d80, 0xc000372d8d, 0x16, 0x0, 0xc0004d94c8, 0xc0002efab0)
bivac    |      /go/src/github.com/camptocamp/bivac/internal/manager/manager.go:254 +0x2cc
bivac    | github.com/camptocamp/bivac/internal/manager.(*Manager).backupVolume(0xc000156d80, 0x17072c0, 0xc0001d0000, 0xc000350200)
bivac    |      /go/src/github.com/camptocamp/bivac/internal/manager/server.go:76 +0x102
bivac    | net/http.HandlerFunc.ServeHTTP(0xc00017fd80, 0x17072c0, 0xc0001d0000, 0xc000350200)
bivac    |      /usr/local/go/src/net/http/server.go:1995 +0x44
bivac    | github.com/camptocamp/bivac/internal/manager.(*Manager).handleAPIRequest.func1(0x17072c0, 0xc0001d0000, 0xc000350200)
bivac    |      /go/src/github.com/camptocamp/bivac/internal/manager/server.go:51 +0x1e7
bivac    | net/http.HandlerFunc.ServeHTTP(0xc0004ef320, 0x17072c0, 0xc0001d0000, 0xc000350200)
bivac    |      /usr/local/go/src/net/http/server.go:1995 +0x44
bivac    | github.com/gorilla/mux.(*Router).ServeHTTP(0xc000126070, 0x17072c0, 0xc0001d0000, 0xc000350200)
bivac    |      /go/src/github.com/camptocamp/bivac/vendor/github.com/gorilla/mux/mux.go:162 +0x105
bivac    | net/http.serverHandler.ServeHTTP(0xc000354d00, 0x17072c0, 0xc0001d0000, 0xc0000c9e00)
bivac    |      /usr/local/go/src/net/http/server.go:2774 +0xa8
bivac    | net/http.(*conn).serve(0xc000179400, 0x170b4c0, 0xc0002d2cc0)
bivac    |      /usr/local/go/src/net/http/server.go:1878 +0x851
bivac    | created by net/http.(*Server).Serve
bivac    |      /usr/local/go/src/net/http/server.go:2884 +0x2f4
```

And for reference my docker-compose.yml (still the same as in the first post):
```
version: '2' 
services:
  bivac:
    image: camptocamp/bivac:2.1.0-encoded-output
    command: manager
    container_name: bivac
    restart: always
    ports:
      - "8182:8182"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/backups:/var/backups"
    environment:
      BIVAC_SERVER_PSK: my-psk
      RESTIC_PASSWORD: my-pw
      BIVAC_TARGET_URL: /var/backups
      BIVAC_AGENT_IMAGE: camptocamp/bivac:2.1.0-encoded-output
```

**Comment by dhilgarth** [comment]
I can confirm these results. Getting exactly the same error.

**Comment by cryptobioz** [comment]
Thank you very much for you help @dhilgarth @neuhausf!
I made changes to get rid of spaces in the agent output content. Would you please try again with the image `camptocamp/bivac:2.1.0-encoded-output`?

**Comment by cryptobioz** [comment]
@neuhausf Did you try to decode this content? Looks like it's truncated which would explain why nothing is working properly...

**Comment by cryptobioz** [comment]
Yes but, the spaces are removed before decoding the output as you can see here: https://github.com/camptocamp/bivac/blob/fix/string-escape-code/internal/manager/backup.go#L81

I updated the image to display the _trimed-spaces-output_ in the error message, you can try again but I doubt it will give us more informations.

**Comment by neuhausf** [comment]
I tried again. Here is the log in the container:
https://gist.github.com/neuhausf/14b8ba84d5e3f2070420e53e63a67bec

There are some spaces in the base64 output, although I don't know if good or bad 😉 
![image](https://user-images.githubusercontent.com/7963239/67085465-27b86200-f19f-11e9-9e2f-71546244437c.png)

**Comment by cryptobioz** [comment]
Oh, I think I got it... Here's the new image with all whitespaces removed: `camptocamp/bivac:2.1.0-encoded-output`.

**Comment by neuhausf** [comment]
@cryptobioz I think you're the man 👍 
Now the logs in the container seem to be correct:
https://gist.github.com/neuhausf/df72eb32eacdc31fad067c83a2476873
On the host I don't see any logs with docker-compose logs, but I guess these logs are not generated when running a backup manually?
```
root@123:9922:/srv/bivac# docker-compose logs
Attaching to bivac
bivac    | time="2019-10-18T11:29:04Z" level=info msg="Starting backup manager..."
bivac    | time="2019-10-18T11:29:04Z" level=info msg="Listening on 0.0.0.0:8182"
root@123:9922:/srv/bivac# 
```

**Comment by cryptobioz** [comment]
Yeah! \o/

But you're right, the manager should log that you manually requested a backup...

**Comment by dhilgarth** [comment]
I am sorry to say, but I can't report success. I am still getting errors. I have used the images digest to confirm that I am using the latest version of that `camptocamp/bivac:2.1.0-encoded-output`:
 ```
daniel@linux-host:/opt/docker$ docker images --digests
REPOSITORY                    TAG                    DIGEST                                                                    IMAGE ID            CREATED             SIZE
camptocamp/bivac              2.1.0-encoded-output   sha256:efe87ea7903e785d46bbf342e5f038f352dd2c24075c71ddbd4a26e0382741bc   bb30691bb458        27 minutes ago      218MB
```

I am getting base64 decoding errors:
```2019-10-18T12:34:33.562209200Z time="2019-10-18T12:34:33Z" level=error msg="failed to decode agent output of `docker_grafana-data` : illegal base64 data at input byte 0 -> `{\"type\":\"success\",\"content\":{\"backup\":{\"stdout\":\"{\\\"message_type\\\":\\\"status\\\",\\\"percent_done\\\":0,\\\"total_files\\\":1,\\\"total_bytes\\\":479232}\\n{\\\"message_type\\\":\\\"status\\\",\\\"percent_done\\\":0,\\\"total_files\\\":1,\\\"total_bytes\\\":479232,\\\"current_files\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data/grafana.db\\\"]}\\n{\\\"message_type\\\":\\\"status\\\",\\\"percent_done\\\":1,\\\"total_files\\\":1,\\\"total_bytes\\\":479232,\\\"bytes_done\\\":479232,\\\"current_files\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data/grafana.db\\\"]}\\n{\\\"message_type\\\":\\\"status\\\",\\\"percent_done\\\":1,\\\"total_files\\\":1,\\\"total_bytes\\\":479232,\\\"bytes_done\\\":479232,\\\"current_files\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data/grafana.db\\\"]}\\n{\\\"message_type\\\":\\\"status\\\",\\\"seconds_elapsed\\\":1,\\\"percent_done\\\":1,\\\"total_files\\\":1,\\\"files_done\\\":1,\\\"total_bytes\\\":479232,\\\"bytes_done\\\":479232}\\n{\\\"message_type\\\":\\\"status\\\",\\\"seconds_elapsed\\\":1,\\\"percent_done\\\":1,\\\"total_files\\\":1,\\\"files_done\\\":1,\\\"total_bytes\\\":479232,\\\"bytes_done\\\":479232}\\n{\\\"message_type\\\":\\\"summary\\\",\\\"files_new\\\":0,\\\"files_changed\\\":1,\\\"files_unmodified\\\":0,\\\"dirs_new\\\":0,\\\"dirs_changed\\\":5,\\\"dirs_unmodified\\\":0,\\\"data_blobs\\\":1,\\\"tree_blobs\\\":6,\\\"data_added\\\":481292,\\\"total_files_processed\\\":1,\\\"total_bytes_processed\\\":479232,\\\"total_duration\\\":1.0148517,\\\"snapshot_id\\\":\\\"71d76701\\\"}\\n\",\"rc\":0},\"forget\":{\"stdout\":\"[{\\\"tags\\\":null,\\\"host\\\":\\\"linux-host\\\",\\\"paths\\\":null,\\\"keep\\\":[{\\\"time\\\":\\\"2019-10-18T12:34:24.9984045Z\\\",\\\"parent\\\":\\\"d4ec9362bf9a86001eefc66cd93e4085e02c0d24439a334252fada5db4d0e9f6\\\",\\\"tree\\\":\\\"0b7d1afa8c6bd94bc678931a826e15702899d20dd38824901bbbc5ed037a988f\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"71d76701590d4edd2c8fb0c9f36a51b86536efe0d91e4b221ca9e634f5eafddd\\\",\\\"short_id\\\":\\\"71d76701\\\"},{\\\"time\\\":\\\"2019-10-16T10:36:23.8850742Z\\\",\\\"parent\\\":\\\"699d36032370246bb6423c6f092afdf24c38c5ce2bf919a0bcf5d4aab04bdd02\\\",\\\"tree\\\":\\\"e54fd85f8cc501c7b67f3c581a1ed6795b2576cf14246dd205922a667160a57b\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"d4ec9362bf9a86001eefc66cd93e4085e02c0d24439a334252fada5db4d0e9f6\\\",\\\"short_id\\\":\\\"d4ec9362\\\"},{\\\"time\\\":\\\"2019-10-15T11:36:03.5974839Z\\\",\\\"parent\\\":\\\"b3d9a16777075ff8662b687554ed41fd5d4e79b72afb6bafa80c255cddc62aa5\\\",\\\"tree\\\":\\\"e41759da0a7547517a18a5b5f455aa37a24a0f2954472df00e577d975555008c\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"699d36032370246bb6423c6f092afdf24c38c5ce2bf919a0bcf5d4aab04bdd02\\\",\\\"short_id\\\":\\\"699d3603\\\"},{\\\"time\\\":\\\"2019-10-14T12:27:12.085066Z\\\",\\\"parent\\\":\\\"6e6c76bb71838a78c48216b35c0d29ab5b125ecaf671138b8827e9c46dcfbcaf\\\",\\\"tree\\\":\\\"b4679b620bfbbb616a9420f351c458b10f91d1c849758cb26621ba343f2167b5\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"b3d9a16777075ff8662b687554ed41fd5d4e79b72afb6bafa80c255cddc62aa5\\\",\\\"short_id\\\":\\\"b3d9a167\\\"},{\\\"time\\\":\\\"2019-10-13T13:26:44.0686839Z\\\",\\\"parent\\\":\\\"6bab44ed4d02746c7cebccbe9488511dbbb7eb9e95a63b82efa3d5ccca74ca91\\\",\\\"tree\\\":\\\"36d6daf6f55abbc7f6842f4fb684ac71f5907b1e8150f429837d3f3f04d093dc\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"6e6c76bb71838a78c48216b35c0d29ab5b125ecaf671138b8827e9c46dcfbcaf\\\",\\\"short_id\\\":\\\"6e6c76bb\\\"},{\\\"time\\\":\\\"2019-10-12T14:26:23.4004481Z\\\",\\\"parent\\\":\\\"10e82c946622d68ec3cacd712bb0746a02189ea212c612ae2d86a676938474e5\\\",\\\"tree\\\":\\\"c52ab0f8d315696c56c4900b544f5d9c5b3f5c95dc9408d583f06aed501dc22e\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"6bab44ed4d02746c7cebccbe9488511dbbb7eb9e95a63b82efa3d5ccca74ca91\\\",\\\"short_id\\\":\\\"6bab44ed\\\"},{\\\"time\\\":\\\"2019-10-11T15:19:59.6114724Z\\\",\\\"tree\\\":\\\"67be7b8273c4b84a6aca2450e00dfb1616107a5e87605267f73fac5561bf5e72\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"10e82c946622d68ec3cacd712bb0746a02189ea212c612ae2d86a676938474e5\\\",\\\"short_id\\\":\\\"10e82c94\\\"}],\\\"remove\\\":null,\\\"reasons\\\":[{\\\"snapshot\\\":{\\\"time\\\":\\\"2019-10-18T12:34:24.9984045Z\\\",\\\"parent\\\":\\\"d4ec9362bf9a86001eefc66cd93e4085e02c0d24439a334252fada5db4d0e9f6\\\",\\\"tree\\\":\\\"0b7d1afa8c6bd94bc678931a826e15702899d20dd38824901bbbc5ed037a988f\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\"},\\\"matches\\\":[\\\"dailysnapshot\\\"],\\\"counters\\\":{\\\"daily\\\":14}},{\\\"snapshot\\\":{\\\"time\\\":\\\"2019-10-16T10:36:23.8850742Z\\\",\\\"parent\\\":\\\"699d36032370246bb6423c6f092afdf24c38c5ce2bf919a0bcf5d4aab04bdd02\\\",\\\"tree\\\":\\\"e54fd85f8cc501c7b67f3c581a1ed6795b2576cf14246dd205922a667160a57b\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\"},\\\"matches\\\":[\\\"dailysnapshot\\\"],\\\"counters\\\":{\\\"daily\\\":13}},{\\\"snapshot\\\":{\\\"time\\\":\\\"2019-10-15T11:36:03.5974839Z\\\",\\\"parent\\\":\\\"b3d9a16777075ff8662b687554ed41fd5d4e79b72afb6bafa80c255cddc62aa5\\\",\\\"tree\\\":\\\"e41759da0a7547517a18a5b5f455aa37a24a0f2954472df00e577d975555008c\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\"},\\\"matches\\\":[\\\"dailysnapshot\\\"],\\\"counters\\\":{\\\"daily\\\":12}},{\\\"snapshot\\\":{\\\"time\\\":\\\"2019-10-14T12:27:12.085066Z\\\",\\\"parent\\\":\\\"6e6c76bb71838a78c48216b35c0d29ab5b125ecaf671138b8827e9c46dcfbcaf\\\",\\\"tree\\\":\\\"b4679b620bfbbb616a9420f351c458b10f91d1c849758cb26621ba343f2167b5\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\"},\\\"matches\\\":[\\\"dailysnapshot\\\"],\\\"counters\\\":{\\\"daily\\\":11}},{\\\"snapshot\\\":{\\\"time\\\":\\\"2019-10-13T13:26:44.0686839Z\\\",\\\"parent\\\":\\\"6bab44ed4d02746c7cebccbe9488511dbbb7eb9e95a63b82efa3d5ccca74ca91\\\",\\\"tree\\\":\\\"36d6daf6f55abbc7f6842f4fb684ac71f5907b1e8150f429837d3f3f04d093dc\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\"},\\\"matches\\\":[\\\"dailysnapshot\\\"],\\\"counters\\\":{\\\"daily\\\":10}},{\\\"snapshot\\\":{\\\"time\\\":\\\"2019-10-12T14:26:23.4004481Z\\\",\\\"parent\\\":\\\"10e82c946622d68ec3cacd712bb0746a02189ea212c612ae2d86a676938474e5\\\",\\\"tree\\\":\\\"c52ab0f8d315696c56c4900b544f5d9c5b3f5c95dc9408d583f06aed501dc22e\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\"},\\\"matches\\\":[\\\"dailysnapshot\\\"],\\\"counters\\\":{\\\"daily\\\":9}},{\\\"snapshot\\\":{\\\"time\\\":\\\"2019-10-11T15:19:59.6114724Z\\\",\\\"tree\\\":\\\"67be7b8273c4b84a6aca2450e00dfb1616107a5e87605267f73fac5561bf5e72\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\"},\\\"matches\\\":[\\\"dailysnapshot\\\"],\\\"counters\\\":{\\\"daily\\\":8}}]}]\\n\",\"rc\":0},\"snapshots\":{\"stdout\":\"[{\\\"time\\\":\\\"2019-10-11T15:19:59.6114724Z\\\",\\\"tree\\\":\\\"67be7b8273c4b84a6aca2450e00dfb1616107a5e87605267f73fac5561bf5e72\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"10e82c946622d68ec3cacd712bb0746a02189ea212c612ae2d86a676938474e5\\\",\\\"short_id\\\":\\\"10e82c94\\\"},{\\\"time\\\":\\\"2019-10-12T14:26:23.4004481Z\\\",\\\"parent\\\":\\\"10e82c946622d68ec3cacd712bb0746a02189ea212c612ae2d86a676938474e5\\\",\\\"tree\\\":\\\"c52ab0f8d315696c56c4900b544f5d9c5b3f5c95dc9408d583f06aed501dc22e\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"6bab44ed4d02746c7cebccbe9488511dbbb7eb9e95a63b82efa3d5ccca74ca91\\\",\\\"short_id\\\":\\\"6bab44ed\\\"},{\\\"time\\\":\\\"2019-10-13T13:26:44.0686839Z\\\",\\\"parent\\\":\\\"6bab44ed4d02746c7cebccbe9488511dbbb7eb9e95a63b82efa3d5ccca74ca91\\\",\\\"tree\\\":\\\"36d6daf6f55abbc7f6842f4fb684ac71f5907b1e8150f429837d3f3f04d093dc\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"6e6c76bb71838a78c48216b35c0d29ab5b125ecaf671138b8827e9c46dcfbcaf\\\",\\\"short_id\\\":\\\"6e6c76bb\\\"},{\\\"time\\\":\\\"2019-10-14T12:27:12.085066Z\\\",\\\"parent\\\":\\\"6e6c76bb71838a78c48216b35c0d29ab5b125ecaf671138b8827e9c46dcfbcaf\\\",\\\"tree\\\":\\\"b4679b620bfbbb616a9420f351c458b10f91d1c849758cb26621ba343f2167b5\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"b3d9a16777075ff8662b687554ed41fd5d4e79b72afb6bafa80c255cddc62aa5\\\",\\\"short_id\\\":\\\"b3d9a167\\\"},{\\\"time\\\":\\\"2019-10-15T11:36:03.5974839Z\\\",\\\"parent\\\":\\\"b3d9a16777075ff8662b687554ed41fd5d4e79b72afb6bafa80c255cddc62aa5\\\",\\\"tree\\\":\\\"e41759da0a7547517a18a5b5f455aa37a24a0f2954472df00e577d975555008c\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"699d36032370246bb6423c6f092afdf24c38c5ce2bf919a0bcf5d4aab04bdd02\\\",\\\"short_id\\\":\\\"699d3603\\\"},{\\\"time\\\":\\\"2019-10-16T10:36:23.8850742Z\\\",\\\"parent\\\":\\\"699d36032370246bb6423c6f092afdf24c38c5ce2bf919a0bcf5d4aab04bdd02\\\",\\\"tree\\\":\\\"e54fd85f8cc501c7b67f3c581a1ed6795b2576cf14246dd205922a667160a57b\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"d4ec9362bf9a86001eefc66cd93e4085e02c0d24439a334252fada5db4d0e9f6\\\",\\\"short_id\\\":\\\"d4ec9362\\\"},{\\\"time\\\":\\\"2019-10-18T12:34:24.9984045Z\\\",\\\"parent\\\":\\\"d4ec9362bf9a86001eefc66cd93e4085e02c0d24439a334252fada5db4d0e9f6\\\",\\\"tree\\\":\\\"0b7d1afa8c6bd94bc678931a826e15702899d20dd38824901bbbc5ed037a988f\\\",\\\"paths\\\":[\\\"/var/lib/docker/volumes/docker_grafana-data/_data\\\"],\\\"hostname\\\":\\\"linux-host\\\",\\\"username\\\":\\\"root\\\",\\\"id\\\":\\\"71d76701590d4edd2c8fb0c9f36a51b86536efe0d91e4b221ca9e634f5eafddd\\\",\\\"short_id\\\":\\\"71d76701\\\"}]\\n\",\"rc\":0}}}`"
```

To me, this looks like it is trying to interpret a JSON as Base64

**Comment by cryptobioz** [comment]
@dhilgarth I think your agent isn't using the same image. Did you set the environnement variable `BIVAC_AGENT_IMAGE=camptocamp/bivac:2.1.0-encoded-output`?

**Comment by dhilgarth** [comment]
Aha.
Adding  `BIVAC_AGENT_IMAGE: camptocamp/bivac:2.1.0-encoded-output` seems to have helped.

Now it looks like the backup is successful

**Comment by cryptobioz** [comment]
Ok, great! I'm working on a cleaner fix and will release a new minor version asap.

Thank you very much @neuhausf and @dhilgarth for you help!

**Comment by cryptobioz** [comment]
@neuhausf @dhilgarth Would you please try again (I hope the last) with the image `camptocamp/bivac:2.1.0-encoded-output`?
If it works as expected, I'll merge to master and publish a new release.

**Comment by dhilgarth** [comment]
Looking good!

**Comment by cryptobioz** [comment]
The new release has been published: [2.2.0](https://github.com/camptocamp/bivac/releases/tag/2.2.0).

Thank you very much @dhilgarth and @neuhausf for your help!

**Comment by dhilgarth** [comment]
Looking good, thanks for the fix! :)

**Comment by varac** [comment]
Unfortunately we bumped into this with `:latest` as with `:2.2`.
Most volumes fail to backup like this:

```
root@brix:/etc/docker/compose/bivac# docker-compose exec bivac bivac -v backup unifi_controller                                                                                          
Backing up `unifi_controller'...
ID: unifi_controller
Name: unifi_controller
Mountpoint: /var/lib/docker/volumes/unifi_controller/_data
Backup date: 2020-07-01 19:26:37
Backup status: Unknown
Logs:

        testInit
        init
        backup
        forget
```

In the journal logs I find this:

```
Jul 02 10:49:36 brix docker-compose[28176]: bivac_1  | time="2020-07-02T08:49:36Z" level=error msg="failed to decode agent output of `unifi_controller` : illegal base64 data at input byte 9 -> CONTAINER_PARTIAL_MESSAGE=trueeyJ0eXBlIjoic3VjY2Vzc...
```

The last backup is still from yesterday:

```
root@brix:/etc/docker/compose/bivac# docker-compose exec bivac bivac volumes | grep unifi_controller
unifi_controller                unifi_controller                brix            /var/lib/docker/volumes/unifi_controller/_data                  2020-07-01 19:26:37     Unknown          false
```

Although restic reports a successful backup:

```
root@brix:/etc/docker/compose/bivac# docker-compose exec bivac bivac restic --volume unifi_controller snapshots                                                                          
ID        Time                 Host        Tags        Paths
-----------------------------------------------------------------------------------------------------                                                                                    
accfb509  2020-06-30 22:18:35  brix                    /var/lib/docker/volumes/unifi_controller/_data                                                                                    
417a4f00  2020-07-01 19:26:37  brix                    /var/lib/docker/volumes/unifi_controller/_data                                                                                    
8f9e3888  2020-07-02 08:49:04  brix                    /var/lib/docker/volumes/unifi_controller/_data                                                                                    
-----------------------------------------------------------------------------------------------------                                                                                    
3 snapshots
```

The weird thing is: We have two servers we use bivac with, with the same `docker-compose.yml`, the only difference is the docker version. The one working has `docker-ce 19.03.9` from docker upstream, this one which has these issues has `docker 18.09.1` from debian. Could this be the problem ?

**Comment by varac** [comment]
Btw, I mirrored one failing volume from the problem host to the other one, and there it backs up fine.
I also tried the ` BIVAC_AGENT_IMAGE: camptocamp/bivac:2.1.0-encoded-output` approach but this didn't work at all.

**Comment by dhilgarth** [comment]
Are you using the version 2.2.0 both as the image of the container as well as the agent image?

```version: "3.7"

services:
  backup-bivac:
    image: camptocamp/bivac:2.2.0 # <<----
    command: "manager -v"
    environment:
      AZURE_ACCOUNT_NAME: sovartobackups
      AZURE_ACCOUNT_KEY: ${AZURE_ACCOUNT_KEY}
      BIVAC_TARGET_URL: azure:backup-by-bivac:/
      RESTIC_PASSWORD: ${BACKUP_PASSPHRASE}
      BIVAC_SERVER_PSK: abc
      BIVAC_AGENT_IMAGE: camptocamp/bivac:2.2.0 #<<----
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


```

**Comment by varac** [comment]
Yes, I have: 

```
version: '3.3'

services:
  bivac:
    # https://hub.docker.com/r/camptocamp/bivac/tags
    image: camptocamp/bivac:latest
    command: manager
    ports:
      - "127.0.0.1:8182:8182/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./files/known_hosts:/root/.ssh/known_hosts"
      - "./secrets/id_ed25519:/root/.ssh/id_ed25519"
    environment:
      BIVAC_TARGET_URL: sftp://...
      BIVAC_SERVER_PSK: "...."
      BIVAC_AGENT_IMAGE: camptocamp/bivac:latest
      BIVAC_VERBOSE: "true"
      BIVAC_LOG_LEVEL: debug
      # https://restic.readthedocs.io/en/latest/040_backup.html#environment-variables                                                                 
      RESTIC_PASSWORD: "...."
```

**Comment by varac** [comment]
So I can confirm that upgrading docker from `18.09.1` to `19.03.9` doesn't help unfortunately.

**Comment by varac** [comment]
Should I create an own issue for this failure or should this issue get reopened ?

**Comment by varac** [comment]
I created #350.
